DropDownList_SelectList_Training/Controllers/CityController.cs
using BusinessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace DropDownList_SelectList_Training.Controllers
{
    public class CityController : Controller
    {
        ICityService _cityService;

        public CityController(ICityService cityService)
        {
            _cityService = cityService;
        }

        public async Task<IActionResult> Index()
        {
            List<City> cities = await _cityService.GetCityWithCountryAsync();
            return View(cities);
        }

        [HttpGet]
        public async Task<IActionResult> AddCity()
        {
            ViewBag.Countries = await _cityService.selectListCountryAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCity(City city)
        {
            try
            {
                await _cityService.InsertAsync(city);
                return RedirectToAction(nameof(Index), nameof(City));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Şehir eklerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Countries = await _cityService.selectListCountryAsync();
                return View(city);
            }
        }

        public async Task<IActionResult> DeleteCity(int id)
        {
            City city = await _cityService.GetByIdAsync(id);
            if (city != null)
            {
                await _cityService.DeleteAsync(city);
            }
            return RedirectToAction(nameof(Index), nameof(City));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCity(int id)
        {
            City city = await _cityService.GetByIdAsync(id);
            if (city != null)
            {
                ViewBag.Countries = await _cityService.selectListCountryAsync();
                return View(city);
            }
            return RedirectToAction(nameof(Index), nameof(City));
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCity(City city)
        {
            try
            {
                await _cityService.UpdateAsync(city);
                return RedirectToAction(nameof(Index), nameof(City));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Şehir düzenlerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Countries = await _cityService.selectListCountryAsync();
                return View(city);
            }
        }
    }
}

DropDownList_SelectList_Training/Controllers/CountryController.cs
using BusinessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace DropDownList_SelectList_Training.Controllers
{
    public class CountryController : Controller
    {
        ICountryService _countryService;

        public CountryController(ICountryService countryService)
        {
            _countryService = countryService;
        }

        public async Task<IActionResult> Index()
        {
            List<Country> countries = await _countryService.GetAllAsync();
            return View(countries);
        }

        [HttpGet]
        public IActionResult AddCountry()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddCountry(Country country)
        {
            try
            {
                await _countryService.InsertAsync(country);
                return RedirectToAction(nameof(Index), nameof(Country));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Ülke eklerken bir hata oluştu!!! Hata: {ex.Message}";
                return View(country);
            }
            
        }

        public async Task<IActionResult> DeleteCountry(int id)
        {
            Country country = await _countryService.GetByIdAsync(id);
            if (country != null)
            {
                await _countryService.DeleteAsync(country);
            }
            return RedirectToAction(nameof(Index), nameof(Country));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateCountry(int id)
        {
            Country country = await _countryService.GetByIdAsync(id);
            if(country != null)
            {
                return View(country);
            }
            return RedirectToAction(nameof(Index), nameof(Country));
        }
        [HttpPost]
        public async Task<IActionResult> UpdateCountry(Country country)
        {
            try
            {
                await _countryService.UpdateAsync(country);
                return RedirectToAction(nameof(Index), nameof(Country));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Ülke düzenlerken bir hata oluştu!!! Hata: {ex.Message}";
                return View(country);
            }
            
        }
    }
}

DropDownList_SelectList_Training/Controllers/EmployeeController.cs
using BusinessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;

namespace DropDownList_SelectList_Training.Controllers
{
    public class EmployeeController : Controller
    {
        IEmployeeService _employeeService;

        public EmployeeController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        public async Task<IActionResult> Index()
        {
            List<Employee> employees = await _employeeService.GetEmployeesWithDepartmanAsync();
            return View(employees);
        }

        [HttpGet]
        public async Task<IActionResult> AddEmployee()
        {
            ViewBag.Departments = await _employeeService.selectListDepartmentsAsync();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddEmployee(Employee employee)
        {
            try
            {
                await _employeeService.InsertAsync(employee);
                return RedirectToAction(nameof(Index), nameof(Employee));
            }
            catch(Exception ex)
            {
                ViewBag.Exception = $"Çalışan eklerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Departments = await _employeeService.selectListDepartmentsAsync();
                return View(employee);
            }
            
        }

        public async Task<IActionResult> DeleteEmployee(int id)
        {
            Employee employee = await _employeeService.GetByIdAsync(id);
            if (employee != null)
            {
                await _employeeService.DeleteAsync(employee);
            }
            return RedirectToAction(nameof(Index), nameof(Employee));
        }

        [HttpGet]
        public async Task<IActionResult> UpdateEmployee(int id)
        {
            Employee employee = await _employeeService.GetByIdAsync(id);
            if (employee != null)
            {
                ViewBag.Departments = await _employeeService.selectListDepartmentsAsync();
                return View(employee);
            }
            return RedirectToAction(nameof(Index), nameof(Employee));

        }
        [HttpPost]
        public async Task<IActionResult> UpdateEmployee(Employee employee)
        {
            try
            {
                await _employeeService.UpdateAsync(employee);
                return RedirectToAction(nameof(Index), nameof(Employee));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Çalışan düzenlerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Departments = await _employeeService.selectListDepartmentsAsync();
                return View(employee);
            }
            
        }
    }
}

DropDownList_SelectList_Training/Controllers/PersonController.cs
using BusinessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DropDownList_SelectList_Training.Controllers
{
    public class PersonController : Controller
    {
        IPersonService _personService;

        public PersonController(IPersonService personService)
        {
            _personService = personService;
        }

        public async Task<IActionResult> Index()
        {
            List<Person> people = await _personService.GetPersonWithCountryAndCityAsync();
            return View(people);
        }

        [HttpGet]
        public async Task<IActionResult> AddPerson()
        {
            ViewBag.Countries = await _personService.selectListCountryAsync();

            //Alternatif
            //ViewBag.Countries = new SelectList(await _personService.Countries, "Id", "Name");
            
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddPerson(Person person)
        {
            try
            {
                await _personService.InsertAsync(person);
                return RedirectToAction(nameof(Index), nameof(Person));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Kişi eklerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Countries = await _personService.selectListCountryAsync();
                return View(person);
            }
        }

        public async Task<IActionResult> DeletePerson(int id)
        {
            Person person = await _personService.GetByIdAsync(id);
            if (person != null)
            {
                await _personService.DeleteAsync(person);
            }
            return RedirectToAction(nameof(Index), nameof(Person));
        }

        [HttpGet]
        public async Task<IActionResult> UpdatePerson(int id)
        {
            Person person = await _personService.GetByIdAsync(id);
            if (person != null)
            {
                ViewBag.Countries = await _personService.selectListCountryAsync();
                return View(person);
            }
            return RedirectToAction(nameof(Index), nameof(Person));
        }
        [HttpPost]
        public async Task<IActionResult> UpdatePerson(Person person)
        {
            try
            {
                await _personService.UpdateAsync(person);
                return RedirectToAction(nameof(Index), nameof(Person));
            }
            catch (Exception ex)
            {
                ViewBag.Exception = $"Kişi düzenlerken bir hata oluştu!!! Hata: {ex.Message}";
                ViewBag.Countries = await _personService.selectListCountryAsync();
                return View(person);
            }
        }

        public async Task<JsonResult> selectListCity(int id)
        {
            try
            {
                return Json(await _personService.selectListCityAsync(id));
            }
            catch
            {
                return Json(null);
            }
            
        }
    }
}

DropDownList_SelectList_Training/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DropDownList_SelectList_Training</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DropDownList_SelectList_Training.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Çalışanlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departmanlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Ülkeler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Şehirler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="Index">Kişiler</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DropDownList_SelectList_Training
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>